# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: braiam
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: mentorala
# "service" is the name of this project. This will also be added to your AWS resource names.
service: project-test

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    dockerizePip: true

package:
  exclude:
    - node_modules/**
    - venv/**
    - .venv/**
    - tests/**
    - .git/**
    - .github/**
    - .gitignore

provider:
  name: aws
  runtime: python3.12
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
